# Generated by Django 6.0.1 on 2026-02-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='prenom',
            field=models.CharField(max_length=150),
        ),
    ]
