# Generated by Django 6.0.1 on 2026-02-18 20:48

from django.db import migrations, models


def normalize_student_levels(apps, schema_editor):
    Student = apps.get_model("web", "Student")
    mapping = {
        "L1": "L1",
        "L2": "L2",
        "L3": "L3",
        "M1": "M1",
        "M2": "M2",
        "LICENCE1": "L1",
        "LICENCE2": "L2",
        "LICENCE3": "L3",
        "LICENSE1": "L1",
        "LICENSE2": "L2",
        "LICENSE3": "L3",
        "MASTER1": "M1",
        "MASTER2": "M2",
    }
    default_level = "L1"

    for student in Student.objects.all():
        raw = (student.classe or "").strip().upper().replace(" ", "")
        student.classe = mapping.get(raw, default_level)
        student.save(update_fields=["classe"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_student_nom_alter_student_prenom'),
    ]

    operations = [
        migrations.RunPython(normalize_student_levels, noop_reverse),
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2),
        ),
    ]
