# Generated by Django 6.0.1 on 2026-02-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_student_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('PROF', 'Professeur'), ('STUDENT', 'Etudiant')], max_length=10),
        ),
    ]
